baseurl = "https://leosync.xyz/"
languageCode = "en-us"
title = "LeoSync"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
publishdir = "../   "
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-77625809-1"

[params]
    # General information
    author = "igrybkov"
    description = "LeoSync - made learning simpler."
    copyright = "Released under the MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/igrybkov/leosync"

    version = "0.0.1"
    logo = "images/logo.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

[params.palette]
    primary = "indigo"
    accent  = "light green"

[params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"


[social]
	twitter = "igrybkov"
	github  = "igrybkov"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true